name: Docker
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 */1 *' # Every month
  pull_request:
  workflow_dispatch: # Allow manual triggering

env:
  REPO: gianlu33/reactive-tools

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Build
      id: build
      uses: gianlu33/Publish-Docker-Github-Action@main
      with:
        name: ${{ env.REPO }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: ${{ github.event_name != 'schedule' }}
        tag_names: true
        no_push: true
    -
      name: Test
      run: |
        docker run --rm --network=host --detach -e EM_PORT=5000 -e EM_SGX=false gianlu33/reactive-event-manager:latest
        docker run --rm --network=host --detach -e EM_PORT=6000 -e EM_SGX=false gianlu33/reactive-event-manager:latest
        git clone https://github.com/gianlu33/authentic-execution.git
        shopt -s expand_aliases
        alias REACTIVE_TOOLS="docker run --rm --network=host -v $(pwd)/authentic-execution:/usr/src/app/ ${{ env.REPO }}:${{ steps.build.outputs.tag }} reactive-tools"
        REACTIVE_TOOLS --verbose deploy --workspace demo native.json --result ../res.json
        REACTIVE_TOOLS --verbose attest res.json
        REACTIVE_TOOLS --verbose connect res.json
        REACTIVE_TOOLS --verbose output res.json --connection init-server --arg beef
        [ $(curl localhost:48879) -eq 0 ]
        REACTIVE_TOOLS --verbose output res.json --connection trigger-btn
        [ $(curl localhost:48879) -eq 1 ]
        REACTIVE_TOOLS --verbose output res.json --connection trigger-btn
        [ $(curl localhost:48879) -eq 2 ]
    -
      name: Push
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ env.REPO }}:${{ steps.build.outputs.tag }}
        docker logout
