name: Docker
on:
  push:
    branches:
      - master
      - fosdem-21
  schedule:
    - cron: '0 0 1 */1 *' # Every month
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Build and push
      id: docker_build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gianlu33/reactive-tools
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.event_name == 'pull_request' }}
        tag_names: true
    -
      name: Image tag and digest
      run: echo Tag: ${{ steps.docker_build.outputs.tag }} Digest: ${{ steps.docker_build.outputs.digest }}
