name: Docker
on:
  push:
    branches:
      - master
      - fosdem-21
  schedule:
    - cron: '0 0 1 */1 *' # Every month
  pull_request:
  workflow_dispatch: # Allow manual triggering

env:
  CI_REPO: gianlu33/reactive-tools-ci
  REPO: gianlu33/reactive-tools

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.docker_build.outputs.tag }}
    steps:
    -
      uses: actions/checkout@master
    -
      name: Build and push
      id: docker_build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ env.CI_REPO }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: ${{ github.event_name != 'schedule' }}
        tag_names: true
    -
      name: Image tag and digest
      run: echo Built image with tag ${{ steps.docker_build.outputs.tag }} and digest ${{ steps.docker_build.outputs.digest }}

  test-native:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      tag: ${{needs.build.outputs.tag}}
    steps:
    -
      name: pull Authentic Execution repo
      run: git clone https://github.com/gianlu33/authentic-execution.git
    -
      name: run EM
      run: docker run --rm --network=host --detach -e EM_PORT=5000 -e EM_SGX=false gianlu33/reactive-event-manager:latest
    -
      name: deploy demo
      run: docker run --rm --network=host -v $(pwd)/authentic-execution:/usr/src/app/ ${{ env.CI_REPO }}:${{ needs.build.outputs.tag }} reactive-tools --verbose deploy demo/native.json

  publish:
    runs-on: ubuntu-latest
    needs: test-native
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    -
      name: login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: pull
      run: docker pull ${{ env.CI_REPO }}:${{ needs.test-native.outputs.tag }}
    -
      name: tag
      run: docker tag ${{ env.CI_REPO }}:${{ needs.test-native.outputs.tag }} ${{ env.REPO }}:${{ needs.test-native.outputs.tag }}
    -
      name: push
      run: docker push ${{ env.REPO }}:${{needs.test-native.outputs.tag }}
