name: Fosdem
on:
  schedule:
    - cron: '0 0 1 */1 *' # Every month
  workflow_dispatch: # Allow manual triggering

env:
  REPO: gianlu33/reactive-tools:fosdem

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Pull
      run: git clone --branch fosdem-21 https://github.com/gianlu33/reactive-tools.git
    -
      name: Build
      run: cd reactive-tools && docker build -t ${{ env.REPO }} .
    -
      name: Test
      run: |
        docker run --rm --network=host --detach -e EM_PORT=5000 -e EM_SGX=false gianlu33/reactive-event-manager:latest
        docker run --rm --network=host --detach -e EM_PORT=6000 -e EM_SGX=false gianlu33/reactive-event-manager:latest
        git clone https://github.com/gianlu33/authentic-execution.git
        echo -e '#!/bin/bash\nset -eux\ndocker run --rm -it --network=host -v $(pwd)/authentic-execution:/usr/src/app/ ${{ env.REPO }} reactive-tools "$@"' > REACTIVE_TOOLS && chmod +x REACTIVE_TOOLS
        ./REACTIVE_TOOLS --verbose deploy --workspace demo native.json --result ../res.json
        ./REACTIVE_TOOLS --verbose output --config res.json --connection init-server --arg beef
        [ $(curl localhost:48879) -eq 0 ]
        ./REACTIVE_TOOLS --verbose output --config res.json --connection trigger-btn
        [ $(curl localhost:48879) -eq 1 ]
        ./REACTIVE_TOOLS --verbose output --config res.json --connection trigger-btn
        [ $(curl localhost:48879) -eq 2 ]
    -
      name: Push
      run: |
        docker push ${{ env.REPO }}
        docker logout
