name: Test
on:
  pull_request:
  workflow_dispatch: # Allow manual triggering

env:
  SGX_IMAGE: authexec/event-manager-sgx:latest
  SANCUS_IMAGE: authexec/event-manager-sancus:latest
  TRUSTZONE_IMAGE: authexec/event-manager-trustzone:latest
  AESM_CLIENT_IMAGE: authexec/aesm-client:latest
  MANAGER_IMAGE: authexec/attestation-manager
  ADMIN_IMAGE: authexec/reactive-tools:latest

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      run: git clone https://github.com/AuthenticExecution/examples.git
    -
      name: Pull images
      run: |
        docker pull ${{ env.ADMIN_IMAGE }}
        ### Uncomment lines below if other Docker images are needed ###
        #docker pull ${{ env.SGX_IMAGE }}
        #docker pull ${{ env.MANAGER_IMAGE }}:native
        #docker pull ${{ env.SANCUS_IMAGE }}
        #docker pull ${{ env.TRUSTZONE_IMAGE }}
        #docker pull ${{ env.AESM_CLIENT_IMAGE }}
        #docker pull ${{ env.MANAGER_IMAGE }}:sgx
    -
      name: build button-led
      timeout-minutes: 10
      run: |
        cd examples/button-led
        shopt -s expand_aliases
        alias REACTIVE_TOOLS="docker run --rm --network=host -v $(pwd):/usr/src/app/ ${{ env.ADMIN_IMAGE }} reactive-tools"
        REACTIVE_TOOLS --debug build descriptor-local.json
        unalias REACTIVE_TOOLS
        touch completed

